# Generated by Django 4.2.2 on 2023-06-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, verbose_name='Человекопонятный URL'),
        ),
    ]
