# Generated by Django 4.2.2 on 2023-06-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='num_of_version',
            field=models.CharField(default=1, verbose_name='Номер версии'),
        ),
    ]
